controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil: 
    path: /accueil 
    controller: App\Controller\AccueilController::index

contact_submit: 
    path: /contact 
    controller: App\Controller\ContactController::submit
    methods: POST

actualite:
    path: /actualite
    controller: App\Controller\ActualiteController::actualite
