controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

product_list:
    path: /products
    controller: App\Controller\ProductController::show

customer_list:
    path: /customers
    controller: App\Controller\CustomerController::listCustomers

